### ISSUE TITLE
When will 4.0 version be released?

### ISSUE THREAD

**Issue by alartin** [nanoporetech/minknow_lims_interface#3]
Hi guys,
I was notified that there will be lots of changes with coming 4.0 version. Minknow 4.0 has been released for a couple of days, I just wonder how soon lims interface 4.0 will be released since we need to do lots of work based on it for monitor and automation. Thanks a lot!

**Comment by 0x55555555** [comment]
Hi @alartin,

With 4.0 we have unified the two API's into one - so you can access the new minknow_api here: https://github.com/nanoporetech/minknow_api/releases

or install from pypi with: `pip install minknow_api`.

Please see https://github.com/nanoporetech/minknow_api/blob/master/BREAKING_CHANGES_IN_4.0.md for information on changes made to the API for 4.0

**Comment by alartin** [comment]
Hi @jorj1988 ,
Thanks a lot for the quick response! Actually, you have also answered my the other question why there were two APIs. I guess this repo will be archived soon :)
