### ISSUE TITLE
error with list_devices.py

### ISSUE THREAD

**Issue by neuropathbasel** [nanoporetech/minknow_lims_interface#4]
Hello,
I tried to run the code provided  in the Github repository on this Xubuntu 18.04 machine(MinKNOW GUI Installed version: 4.1.22, with a MinION attached via the USB port).

To this end I did create the python environment provided by ONT a virtual environment I did call gRPC
$ /opt/ont/minknow/ont-python/bin/python3.7 -m venv gRPC

After activation
$ source gRPC/bin/activate

I did check the version of python and which protoc and protobuf:

(gRPC) user@meqneuropat15:~/minknow_lims_interface/examples$ python --version
Python 3.7.4
(gRPC) user@meqneuropat15:~/minknow_lims_interface/examples$ which protoc
/usr/bin/protoc
(gRPC) user@meqneuropat15:~/minknow_lims_interface/examples$ pip show protobuf
Name: protobuf
Version: 3.15.8
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: None
Author-email: None
License: 3-Clause BSD License
Location: /home/user/minknow_lims_interface/examples/gRPC/lib/python3.7/site-packages
Requires: six
Required-by: grpcio-tools

I did update pip and installed the packages named in the header of   

$pip install --upgrade pip
$ pip install protobuf grpcio grpcio-tools

and followed the remaining steps given in the header of list_devices.py:

~/minknow_lims_interface$ mkdir ./examples/generated/

(gRPC) user@meqneuropat15:~/minknow_lims_interface$ python -m grpc_tools.protoc \
>        --python_out=./examples/generated/ \
>        --grpc_python_out=./examples/generated/ \
>        -I . \
>        minknow/rpc/*.proto

here I ran into a warning:
minknow/rpc/device.proto:4:1: warning: Import google/protobuf/wrappers.proto is unused.

In the examples folder I did try to run the list_devices.py from this repository without any changes.

(gRPC) user@meqneuropat15:~/minknow_lims_interface/examples$ python list_devices.py

but ended up with this error:
Traceback (most recent call last):
  File "list_devices.py", line 52, in <module>
    response = stub.list_devices(list_request)
  File "/home/user/minknow_lims_interface/examples/gRPC/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/user/minknow_lims_interface/examples/gRPC/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = ""
	debug_error_string = "{"created":"@1618848144.355747439","description":"Error received from peer ipv4:127.0.0.1:9501","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"","grpc_status":12}"

Any suggestion how run this code?
Best wishes
Claus

**Comment by 0x55555555** [comment]
Hi @neuropathbasel,

If you are using MinKNOW 4.x you need to use the newer combined API from here:

https://github.com/nanoporetech/minknow_api

This will allow LIMS like integration, with some additions that were not originally in this API. There is a python module you can `pip install minknow_api` to use it, and examples in that repository.

Hope that helps,
- George
